services:
  - type: static_site
    name: wala-frontend
    buildCommand: "npm ci && npm run build"
    staticPublishPath: "./build"
    plan: free
    envVars:
      - key: REACT_APP_API_URL
        value: https://wala-backend.onrender.com
    headers:
      - path: "/*"
        name: "X-Frame-Options"
        value: "DENY"
      - path: "/*"
        name: "X-Content-Type-Options" 
        value: "nosniff"
    autoDeploy: false 